### ISSUE TITLE
Trying to install and setup the extension

### ISSUE THREAD

**Issue by Zyze2311** [mlsof21/dim-voice#2]
Basically I installed the extension but can't change the keybind as suggested OR figure out how to give it access to my microphone as it has yet to ask for access to it? Am I doing something wrong?

**Comment by mlsof21** [comment]
If this is on Chrome, it has some limitations as to what you can set as the shortcut. Check this short clip to see how to change the shortcut: [Setting shortcut](https://streamable.com/5fyyky). After setting it correctly and setting to `Global`, reload DIM, wait for it to load, then try the shortcut. It should ask for mic permissions.

**Comment by Zyze2311** [comment]
thanks! can't wait to try it out! awesome work!
